# Don't print a new line at the start of the prompt
add_newline = false

[hostname]
format = "[$hostname]($style) "

[username]
format = "[$user]($style)@"

[directory]
truncation_symbol = "…/"
truncation_length = 2

[status]
disabled = false

[time]
disabled = false
format = '[$time]($style) '
style = "white"
time_format = "%H:%M:%S.%3f"

[cmd_duration]
show_milliseconds = true
min_time = 10_000

### all plugins below are disabled
[line_break]
disabled = true

[package]
disabled = true

[python]
disabled = true

[gcloud]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[rust]
disabled = true

[cmake]
disabled = true

[java]
disabled = true

[scala]
disabled = true

[helm]
disabled = true

[ruby]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[perl]
disabled = true
